---
application:
  name: "inventory-backend"
  project: "medinvent-backend"
  organization: "medinvent"
databases:
- type: "MONGODB"
  name: "medinvent"
  version: "3.6"
routers:
- name: "main-inventory-backend"
  routes:
  - application_name: "inventory-backend"
    paths:
    - "/*"
